name: torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.4.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - appdirs=1.4.4
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.2.0
  - automat=22.10.0
  - backcall=0.2.0
  - bcrypt=3.2.2
  - blas=1.0
  - blinker=1.5
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - constantly=15.1.0
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cssselect=1.2.0
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.0.140
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.140
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.2.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.2.2
  - fftw=3.3.10
  - filelock=3.9.0
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - gds-tools=1.5.1.14
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.16.2
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hyperlink=21.0.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.25.1
  - importlib-metadata=6.0.0
  - incremental=22.10.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.10.0
  - itemadapter=0.7.0
  - itemloaders=1.0.6
  - jedi=0.18.1
  - jmespath=1.0.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.6
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.1.14
  - libcufile-dev=1.5.1.14
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcurl=7.87.0
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.0
  - nsight-compute=2022.4.1.6
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=22.0
  - parsel=1.7.0
  - parso=0.8.3
  - partd=1.3.0
  - pathlib2=2.3.7.post1
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.6.0
  - prompt-toolkit=3.0.36
  - protego=0.2.1
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydispatcher=2.0.5
  - pygments=2.11.2
  - pyhamcrest=2.0.4
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - queuelib=1.6.2
  - readline=8.2
  - requests=2.28.1
  - requests-file=1.5.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-image=0.19.2
  - scrapy=2.8.0
  - sentry-sdk=1.15.0
  - service_identity=18.1.0
  - setproctitle=1.2.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tifffile=2021.4.8
  - tk=8.6.12
  - tldextract=3.4.0
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - traitlets=5.7.1
  - twisted=22.2.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - w3lib=1.21.0
  - wandb=0.13.10
  - wcwidth=0.2.5
  - werkzeug=2.1.2
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.13
  - zope.interface=5.4.0
  - zstd=1.5.2
  - pip:
      - ale-py==0.7.5
      - autorom==0.4.2
      - autorom-accept-rom-license==0.5.5
      - beautifulsoup4==4.11.2
      - bs4==0.0.1
      - certifi==2022.12.7
      - cython==0.29.33
      - deepctr==0.9.3
      - fastdtw==0.3.4
      - fuzzytm==2.0.5
      - gensim==4.3.0
      - gym==0.25.2
      - gym-notices==0.0.8
      - gymnasium==0.27.1
      - gymnasium-notices==0.0.1
      - h5py==3.7.0
      - igraph==0.10.4
      - importlib-resources==5.12.0
      - jax-jumpy==0.2.0
      - joblib==1.2.0
      - libtorrent==2.0.7
      - markdown-it-py==2.1.0
      - mdurl==0.1.2
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - pip-search==0.0.12
      - pyfume==0.2.25
      - pygame==2.1.3.dev8
      - python-graphviz==0.20.1
      - python-igraph==0.10.4
      - pytz==2022.7.1
      - pyunicorn==0.6.1
      - rich==13.3.1
      - scikit-learn==1.2.1
      - scipy==1.10.1
      - simpful==2.10.0
      - smart-open==6.3.0
      - soupsieve==2.4
      - texttable==1.6.7
      - threadpoolctl==3.1.0
      - torchsummary==1.5.1
      - tqdm==4.64.1
      - zipp==3.14.0
