# configs/FPT.yaml
data:
  data_path: "./data/FPT.csv"
  features:
    - open
    - high
    - low
    - volume
    - close
  start_train_date: "2023-11-09"
  end_train_date: "2024-03-31"
  start_validation_date: "2024-04-01"
  end_validation_date: "2024-07-31"
  start_test_date: "2024-08-01"
  end_test_date: "2024-11-01"
  ticket: "FPT"
  feature_augmentation:
    enabled: true
    strategies:
      - technical_indicators

environment:
  features_dim: 5
  action_dim: 1
  initial_balance: 10000
  transaction_fee: 0.001

agent:
  train:
    episodes: 2
    critic_coeff: 0.5
    entropy_coeff: 0.01
    eps_clip: 0.2
    gamma: 0.99
    batch_size: 300
    lr_actor: 0.0003
    lr_critic: 0.001
    K_epochs: 20
    action_std: 0.6
    action_std_decay_rate: 0.05
    min_action_std: 0.1
    action_std_decay_freq: 30
    seed: 42
    max_combinations: 2
  save:
    loggers: "./logs"
    checkpoints: "checkpoints"